- name: "Manage Clusters"
  hosts: "{{ target_hosts | default('all') }}"
  connection: local
  gather_facts: false

  vars:
    # The following line is necessary because the generated inventory file
    # has this set to true.  We don't need to use sudo for the following
    # operations.
    ansible_become: false
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: "Execute"
      block:
        - name: "Add access"
          ansible.builtin.include_tasks: ../roles/k8s-cluster-access/tasks/get-temp-access.yml
          vars:
            rbac_template: ../k8s-rbac/namespace-mgmt
            serviceaccount_generate_name: "cluster-mgmt-"
            ttl: 60
        - name: "Execute action"
          ansible.builtin.include_role:
            name: ../roles/get-namespaces
      always:
        - name: "Remove access"
          include_tasks: ../roles/k8s-cluster-access/tasks/remove-access.yml
          ignore_errors: true
