# Build a dynamic group with only matching bastions
# --limit only works with name and groups
- hosts: bastion
  tasks:
    - name: Single host
      block:
        - name: Add only current host to the bastion_filtered group
          ansible.builtin.add_host:
            name: '{{ item }}'
            groups: bastion_filtered
          when: hostvars[item]['tags']['cluster_name'] == cluster_name
          loop: "{{ ansible_play_hosts }}"
      when: cluster_name is defined
      run_once: true

    - name: All hosts
      block:
        - name: Add all hosts running this playbook to the bastion_filtered group
          ansible.builtin.add_host:
            name: '{{ item }}'
            groups: bastion_filtered
          loop: "{{ ansible_play_hosts }}"
      when: cluster_name is not defined
      run_once: true

- hosts: bastion_filtered
  become: true
  roles:
    - role: ../roles/bastion-ocp4-facts # get ocp4 specific facts
      tags: [vm, users, ocp4]
    - role: ../roles/authorized-key # set up users
      tags: [users]
    - role: ../roles/bastion-setup # configure VM
      tags: [vm]
    - role: ../roles/bastion-ocp4-setup # configure ocp4 specific stuff
      tags: [ocp4]
