---
# This playbook setups an Azure Public DNS Zone that has
# - A record pointing to public IP for the bastion
# - A record pointing to private IP of *.apps
# - A record pointing to private IP of api.
# This is useful for Certificate generation through DNS01 challenge
# and to avoid DNS forwarding through the bastion

- hosts: localhost
  gather_facts: false
  connection: local
  become: false

  vars:
    # The following line is necessary because the generated inventory file
    # has this set to true.  We don't need to use sudo for the following
    # operations.
    ansible_become: false
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: Include DNS role
      ansible.builtin.include_role:
        name: ../roles/setup-public-dns-zone
        tasks_from: main
