{
 "title": "AAP Golden Signals Dashboard - by Tenant",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency -  Metric being added to AAP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 }
  },
  {
   "title": "Error Rate - Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "awx_status_total{cluster=\"$cluster\",status=~\"error|failed\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Traffic - Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "awx_status_total{cluster=\"$cluster\",status=~\"pending|running\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Saturation - Instance Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "awx_instance_remaining_capacity{cluster=\"$cluster\"}/awx_instance_capacity{cluster=\"$cluster\"}",
     "legendFormat": "Percent Instance Capacity Remaining"
    }
   ]
  },
  {
   "title": "Additional Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "AAP Hosts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "awx_hosts_total{cluster=\"$cluster\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Saturation - Tower Pod Counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum(kube_pod_info{cluster=\"$cluster\", namespace=\"ansible-automation-platform\"})",
       "legendFormat": "{{cluster}} PodCount"
      }
     ]
    },
    {
     "title": "User Interation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "awx_users_total{cluster=\"$cluster\"}"
      },
      {
       "expr": "awx_sessions_total{cluster=\"$cluster\"}",
       "legendFormat": "{{type}} Sessions"
      }
     ]
    },
    {
     "title": "Traffic - Jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "awx_status_total{cluster=\"$cluster\",status!=\"successful\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Saturation - Instance Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "awx_instance_consumed_capacity{cluster=\"$cluster\"}",
       "legendFormat": "Consumed"
      },
      {
       "expr": "awx_instance_remaining_capacity{cluster=\"$cluster\"}",
       "legendFormat": "Remaining"
      },
      {
       "expr": "awx_instance_capacity{cluster=\"$cluster\"}",
       "legendFormat": "Total Capacity"
      }
     ]
    }
   ]
  }
 ]
}