{
 "title": "AAP Pod Uptime",
 "description": "AAP Pod Uptime Dashboard",
 "tags": [
  "AAP",
  "Uptime"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_start_time, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AAP Controller",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - kube_pod_start_time{namespace=\"ansible-automation-platform\", pod=~\"automation-controller-.*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "AAP Hub API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - kube_pod_start_time{namespace=\"ansible-automation-platform\", pod=~\"automation-hub-api-.*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "AAP Hub Content",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - kube_pod_start_time{namespace=\"ansible-automation-platform\", pod=~\"automation-hub-content-.*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "AAP Endpoint Aavaibility",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_endpoint_address_available{namespace=\"ansible-automation-platform\", cluster=\"$cluster\"}/(kube_endpoint_address_available{namespace=\"ansible-automation-platform\", cluster=\"$cluster\"} + kube_endpoint_address_not_ready{namespace=\"ansible-automation-platform\", cluster=\"$cluster\"}) * 100",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "AAP Hub Redis",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - kube_pod_start_time{namespace=\"ansible-automation-platform\", pod=~\"automation-hub-redis-.*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "AAP Hub Web",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - kube_pod_start_time{namespace=\"ansible-automation-platform\", pod=~\"automation-hub-web-.*\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "AAP Hub Worker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - kube_pod_start_time{namespace=\"ansible-automation-platform\", pod=~\"automation-hub-worker-.*\", cluster=\"$cluster\"})"
    }
   ]
  }
 ]
}