{
 "title": "Alert Analysis",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "severity", "query": { "query": "label_values(ALERTS, severity)" } }
  ]
 },
 "panels": [
  { "title": "Real Time Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Alerts and Clusters",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum (ALERTS{alertstate=\"firing\"}) by (cluster,alertname,severity)"
    }
   ]
  },
  {
   "title": "Total Critical Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"critical\"})"
    }
   ]
  },
  {
   "title": "Total Warning Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"warning\"})"
    }
   ]
  },
  {
   "title": "Total Moderate Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"moderate\"})"
    }
   ]
  },
  {
   "title": "AlertType Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=~\"$severity\"}) by (alertname)"
    }
   ]
  },
  {
   "title": "Cluster Affected Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", cluster!=\"\", severity=~\"$severity\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "Historical Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Most Firing Alerts",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(ALERTS{alertstate=\"firing\",severity=~\"$severity\"}[$__range])) by (alertname)",
       "legendFormat": "{{alertname}}"
      }
     ]
    },
    {
     "title": "Most Affected Clusters",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(ALERTS{alertstate=\"firing\", cluster!=\"\",severity=~\"$severity\"}[$__range])) by (cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  }
 ]
}