---
- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
    groups: "wheel"
    append: true
  with_items: "{{ public_key }}"

- name: Set authorized key from file
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  with_items: "{{ public_key }}"

- name: Ensure sudo access
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: "%wheel        ALL=(ALL)       NOPASSWD: ALL"  # pragma: allowlist secret
