---
collections:
  - name: ansible.posix
    version: 1.4.0
  - name: awx.awx
    version: 21.4.0
  - name: azure.azcollection
    version: 1.13.0
  - name: community.crypto
    version: 2.3.4
  - name: community.general
    version: 5.2.0
  - name: kubernetes.core
    version: 2.3.2
  - name: stolostron.core
    version: 0.0.1
