{
 "title": "AAP Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "awx_running_jobs_total" },
    { "expr": "awx_pending_jobs_total" }
   ]
  },
  {
   "title": "User Interation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "awx_users_total" },
    { "expr": "awx_sessions_total" }
   ]
  },
  {
   "title": "AAP Hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "awx_hosts_total" }
   ]
  },
  {
   "title": "Instance Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "awx_instance_consumed_capacity" },
    {
     "expr": "awx_instance_remaining_capacity"
    }
   ]
  }
 ]
}