{
 "title": "AAP Dashboard - by Tenant",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "awx_running_jobs_total{cluster=\"$cluster\"}"
    },
    {
     "expr": "awx_pending_jobs_total{cluster=\"$cluster\"}"
    },
    {
     "expr": "awx_sessions_total{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "User Interation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "awx_users_total{cluster=\"$cluster\"}"
    },
    {
     "expr": "awx_sessions_total{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "AAP Hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "awx_hosts_total{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Instance Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "awx_instance_consumed_capacity{cluster=\"$cluster\"}"
    },
    {
     "expr": "awx_instance_remaining_capacity{cluster=\"$cluster\"}"
    }
   ]
  }
 ]
}