{
 "title": "Cluster Problem Determination  - by Tenant",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Running, Pending, Error - Jobs & Pod Counts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "awx_status_total{cluster=\"$cluster\",status=~\"pending|running\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "count(kube_pod_info{cluster=\"$cluster\",namespace=\"ansible-automation-platform\"})",
     "legendFormat": "Pod Count"
    },
    {
     "expr": "sum(rate(awx_status_total{cluster=\"$cluster\",status=~\"error\"}[15m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  instance:node_cpu_utilisation:rate1m{cluster=\"$cluster\",job=\"node-exporter\"}\n*\n  instance:node_num_cpu:sum{cluster=\"$cluster\",job=\"node-exporter\"}\n)\n/ scalar(sum(instance:node_num_cpu:sum{cluster=\"$cluster\",job=\"node-exporter\"}))\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{cluster=\"$cluster\",job=\"node-exporter\"}\n/ scalar(count(instance:node_memory_utilisation:ratio{cluster=\"$cluster\",job=\"node-exporter\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Condition",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{cluster=\"$cluster\",status=\"true\"}==1) by (node,condition)"
    }
   ]
  },
  {
   "title": "Containers Waiting/Terminated",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{cluster=\"$cluster\", namespace=\"ansible-automation-platform\"} == 1) by (reason)",
     "legendFormat": "{{ pod }} - {{ reason }}"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{cluster=\"$cluster\", namespace=\"ansible-automation-platform\"} == 1) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Pod Problems",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"cicd-aap-aas-ansible-c-eastus\",namespace=\"ansible-automation-platform\", phase=~\"Failed|Pending|Unknown\"} ) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Number of Alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", cluster=\"$cluster\"}) by (alertname)"
    }
   ]
  }
 ]
}